
export default Object.freeze({
  mainColor: 'green',
  containerBgColor: '#F0F0F0',
  color: {
    primary: '#FCCD3B',
    secondary: '#CCCCCC',
    light: '#F9F9F9',
    dark: '#000000',
    danger: 'red',
    success: 'green',
    gray: 'gray',
    gray2: '#E8E9E8',
    gray3: '#6A6A6A',
    gray4: '#5C5C5C',
    gray5: '#CFCFCF',
    lightGreen: '#6FCE1C',
    errorBorder: '#ed2f2f',
    white: 'white',
  },
  fontFamily: 'Lato',
  fontSize: {
    h1: 30,
    h2: 24,
    h3: 18,
    h4: 14,
    p: 12,
  },
  fontWeight: {
    h1: 900,
    h2: 700,
    h3: 300,
    h4: 700,
    p: 300,
  },
  radius: 8,
  padding: {
    container: 20,
  },
  input: {
    backgroundColor: 'white',
  },
  keyboardAvoidingHeight: 100,
  inputHeightBase: 50,
});
