
export default {
  APP_LANDING: 'AppLanding',
  BUILD_YOUR_SAVING: 'BuildYourSaving',
  BUILD_YOUR_IMPACT: 'BuildYourImpact',
  BUILD_MOVEMENT: 'BuildMovement',
  SIGN_UP_LOGIN: 'SignUpLogin',
  SMS_CODE: 'SmsCode',
  ACCOUNT_TYPE: 'AccountType',
  NAME: 'Name',
  EMAIL: 'Email',
  DATE_OF_BIRTH: 'DateOfBirth',
  HOME_ADDRESS: 'HomeAddress',
  NOTIFICATIONS: 'Notifications',
  THANKS_SHARE: 'ThanksShare',
  ARTIST_NAME: 'ArtistName',
  FIRST_PAGE: 'FirstPage',
  TAB_HOME: 'TabHome',
  TAB_ACTIVITY: 'TabActivity',
  TAB_PROFILE: 'TabProfile',
  DEPOSIT_WITHDRAW: 'DepositWithdraw',
  DEPOSIT_WITHDRAW_DONE: 'DepositWithdrawDone',
  SOLAR_FARM: 'SolarFarm',
  SOLAR_FARMS_LIST: 'SolarFarmsList',
  SOLAR_FARMS_MAP: 'SolarFarmsMap',
  MANAGE_ACCOUNTS: 'ManageAccounts',
  MANAGE_ACCOUNT_DETAILS: 'ManageAccountDetails',
  PERSONAL_DETAILS: 'PersonalDetails',
  REFER_FRIEND: 'ReferFriend',
  TALK_US: 'TalkUs',
  JOIN_FUTURE_SUPER: 'JoinFutureSuper',
  ALL_INVESTMENTS: 'AllInvestments',
};
